backend:
  name: git-gateway
  # name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Data publikacji", name: "date", widget: "datetime" }
          - { label: "Opis", name: "body", widget: "markdown" }
          - label: "Pudełka"
            name: "boxes"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: Photo, name: photo, widget: image }
